// import "reflect-metadata";
// import ReduxProvider from "@/lib/components/ReduxProvider";
// import "@/app/globals.scss";
// import { CounterContextProvider } from "@/lib/context/counter";
// import { SessionProvider } from "@/lib/components/SessionProvider";
// import { getServerSession } from "next-auth";
// import { authOptions } from "@/lib/utilities";
// import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";
// import { ApolloProvider } from "@/lib/utilities/client";


// const __DEV__  = process.env.NODE_ENV !== "production"
// if (__DEV__) {  // Adds messages only in a dev environment
//   loadDevMessages();
//   loadErrorMessages();
// }

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default async function AuthLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const session = await getServerSession(authOptions);
//   return (
//     <SessionProvider session={session}>
//       <ApolloProvider>
//         <CounterContextProvider>
//           <ReduxProvider>
//             <html lang="en">
//               {/* <html lang="en" className={"dark"}> */}
//               <body>
//                 {/* {children} */}
//                 {children}
//               </body>
//             </html>
//           </ReduxProvider>
//         </CounterContextProvider>
//       </ApolloProvider>
//     </SessionProvider>
//   );
// }

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        Auth Layout <hr />
        {children}
      </body>
    </html>
  );
}
