import Nav from "@/components/Nav";
import ReduxProvider from "@/state/ReduxProvider";
import "./globals.scss";
import { CounterContextProvider } from "@/state/context/counter";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CounterContextProvider>
      <ReduxProvider>
        <html lang="en">
          {/* <html lang="en" className={"dark"}> */}
          <body>
            <Nav />
            {/* {children} */}
            {children}
          </body>
        </html>
      </ReduxProvider>
    </CounterContextProvider>
  );
}
